steps:
  - label: "Build flash-attention-nova wheel - CUDA 12.8"
    depends_on: ~
    id: build-wheel-cuda-12-8
    agents:
      queue: "cpu_queue_postmerge"
    commands:
      - export AWS_ACCESS_KEY_ID=$(buildkite-agent secret get AWS_ACCESS_KEY_ID)
      - export AWS_SECRET_ACCESS_KEY=$(buildkite-agent secret get AWS_SECRET_KEY)
      - "pip install modal"
      - "export PATH=/var/lib/buildkite-agent/.local/bin:$PATH"
      - "export MODAL_TOKEN_ID=$(buildkite-agent secret get MODAL_TOKEN_ID)"
      - "export MODAL_TOKEN_SECRET=$(buildkite-agent secret get MODAL_TOKEN_SECRET)"
      - "modal token set --token-id \"$${MODAL_TOKEN_ID}\" --token-secret \"$${MODAL_TOKEN_SECRET}\" --profile=remodlai"
      - "modal profile activate remodlai"
      - "DOCKER_BUILDKIT=1 docker build --ssh default --build-arg MAX_JOBS=32 --build-arg NVCC_THREADS=16 --build-arg CUDA_VERSION=12.8.1 --build-arg PYTHON_VERSION=3.12 --build-arg TORCH_CUDA_ARCH_LIST='8.0 8.6 8.9 9.0 9.0a' --tag flash-attn-ci:build-image --progress plain -f Dockerfile ."
      - "mkdir -p artifacts"
      - "docker run --rm -v $(pwd)/artifacts:/artifacts_host flash-attn-ci:build-image bash -c 'cp -r dist /artifacts_host && chmod -R a+rw /artifacts_host'"
    
      - "WHEEL_FILE=$(ls artifacts/dist/*.whl | head -1)"
      - "modal volume put wheels \"$${WHEEL_FILE}\" \"/packages/$(basename \"$${WHEEL_FILE}\")\""
    env:
      DOCKER_BUILDKIT: "1"
    secrets:
      - MODAL_TOKEN_ID
      - MODAL_TOKEN_SECRET
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_KEY
      - GITHUB_TOKEN

  - label: "Build flash-attention-nova wheel - CUDA 12.9"
    depends_on: ~
    id: build-wheel-cuda-12-9
    agents:
      queue: "cpu_queue_postmerge"
    commands:
      - "export AWS_ACCESS_KEY_ID=$(buildkite-agent secret get AWS_ACCESS_KEY_ID)"
      - export AWS_SECRET_ACCESS_KEY=$(buildkite-agent secret get AWS_SECRET_KEY)
      - "pip install modal"
      - "export PATH=/var/lib/buildkite-agent/.local/bin:$PATH"
      - "export MODAL_TOKEN_ID=$(buildkite-agent secret get MODAL_TOKEN_ID)"
      - "export MODAL_TOKEN_SECRET=$(buildkite-agent secret get MODAL_TOKEN_SECRET)"
      - "modal token set --token-id \"$${MODAL_TOKEN_ID}\" --token-secret \"$${MODAL_TOKEN_SECRET}\" --profile=remodlai"
      - "modal profile activate remodlai"
      - "DOCKER_BUILDKIT=1 docker build --ssh default --build-arg MAX_JOBS=32 --build-arg NVCC_THREADS=16 --build-arg CUDA_VERSION=12.9.1 --build-arg PYTHON_VERSION=3.12 --build-arg TORCH_CUDA_ARCH_LIST='8.0 8.6 8.9 9.0 9.0a' --tag flash-attn-ci:build-image --progress plain -f Dockerfile ."
      - "mkdir -p artifacts"
      - "docker run --rm -v $(pwd)/artifacts:/artifacts_host flash-attn-ci:build-image bash -c 'cp -r dist /artifacts_host && chmod -R a+rw /artifacts_host'"
   
      - "WHEEL_FILE=$(ls artifacts/dist/*.whl | head -1)"
      - "modal volume put wheels \"$${WHEEL_FILE}\" \"/packages/$(basename \"$${WHEEL_FILE}\")\""
 
    env:
      DOCKER_BUILDKIT: "1"

    secrets:
      - MODAL_TOKEN_ID
      - MODAL_TOKEN_SECRET
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_KEY
      - GITHUB_TOKEN

